[target.'cfg(windows)']
rustflags = ["-C", "target-feature=-crt-static"]

[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C",
    "target-feature=-crt-static",
    "-C",
    "link-arg=/OPT:REF",
    "-C",
    "link-arg=/OPT:ICF",
]

[target.x86_64-pc-windows-gnu]
linker = "rust-lld"

[target.x86_64-pc-windows-gnullvm]
rustflags = [
    "-C",
    "link-arg=-fuse-ld=lld",
    "-C",
    "link-arg=-Wl,--gc-sections",
    "-C",
    "link-arg=-Wl,--icf=all",
    "-C",
    "link-self-contained=yes",
]
